name: Enterprise DevOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    name: BUILD STAGE

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          echo "Building Application..."
          echo "Build Success"

  test:

    name: TEST STAGE

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Run Tests
        run: |
          echo "Running Tests..."
          echo "All Tests Passed"

  deploy-dev:

    name: DEPLOY DEV

    runs-on: ubuntu-latest

    needs: test

    environment:
      name: DEV

    steps:

      - name: Deploy DEV
        run: |
          echo "Deploying to DEV"

  deploy-int:

    name: DEPLOY INT

    runs-on: ubuntu-latest

    needs: deploy-dev

    environment:
      name: INT

    steps:

      - name: Deploy INT
        run: |
          echo "Deploying to INT"

  deploy-prod:

    name: DEPLOY PROD

    runs-on: ubuntu-latest

    needs: deploy-int

    environment:
      name: PROD

    steps:

      - name: Deploy PROD
        run: |
          echo "Deploying to PROD"